# Generated by Django 2.2.28 on 2023-06-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dcertt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcertt',
            name='mkjy',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcertt',
            name='zaqwe',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
